// =================== CATÁLOGO DE ELECTIVAS DE FORMACIÓN GENERAL 2025-2 ===================

const ELECTIVAS_FG = [
    // === COMPONENTE CIENTÍFICO TECNOLÓGICO ===
    { id: '417016C', name: 'ESTRATEGIAS PARA EL APRENDIZAJE AUTÓNOMO', credits: 3, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '417017C', name: 'APROPIACIÓN DIGITAL Y APRENDIZAJE SIGNIFICATIVO', credits: 3, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '106030C', name: 'HUMANITAS, CIENCIA, AGRICULTURA Y CAMBIO CLIMÁTICO', credits: 3, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '801127C', name: 'CONFLUENCIA DE REALIDADES: NATURALEZA Y SOCIEDAD', credits: 3, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '801044C', name: 'TALLER DE HABILIDADES INFORMÁTICAS PARA LA GESTIÓN', credits: 3, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '602001C', name: 'EN SUS MARCAS, UN, DOS, TIC, APRENDO', credits: 3, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '201012C', name: 'EDUCACIÓN Y TIC', credits: 3, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '106002C', name: 'INTRODUCCIÓN A LA EXPERIMENTACIÓN CIENTÍFICA', credits: 3, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '102052C', name: 'BIOLOGÍA GENERAL - CIENCIAS', credits: 4, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '116019C', name: 'INTRODUCCIÓN A LAS TECNOLOGÍAS', credits: 2, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '204054C', name: 'ACTIVIDADES DE APRENDIZAJE MEDIADAS POR LAS TIC', credits: 3, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '111023C', name: 'MATEMÁTICAS BÁSICAS', credits: 3, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '111002C', name: 'INTRODUCCIÓN AL MODELAMIENTO MATEMÁTICO', credits: 3, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '116009C', name: 'INTRODUCCIÓN A LAS CIENCIAS NATURALES', credits: 4, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '201022C', name: 'INSTRUMENTOS Y MODELOS DE ANÁLISIS ECONÓMICO PARA LA HISTORIA', credits: 3, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '620013C', name: 'CUIDADOS PALIATIVOS CON ENFOQUE TRANSDISCIPLINAR', credits: 2, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '203019C', name: 'HISTORIA DEL DESARROLLO DE LA INTELIGENCIA ARTIFICIAL Y SUS APLICACIONES PARA LA INVESTIGACIÓN', credits: 3, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '620011C', name: 'ABORDAJE INTEGRAL A LAS PERSONAS CON SITUACIONES ONCOLÓGICAS', credits: 2, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '801157C', name: 'INTELIGENCIA DE NEGOCIOS Y ANALÍTICA DE DATOS PARA LA GESTIÓN', credits: 3, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '802064C', name: 'SEGURIDAD DE LA INFORMACIÓN FINANCIERA Y CONTABLE', credits: 3, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '415006C', name: 'NUEVAS TECNOLOGÍAS Y EDUCACIÓN', credits: 3, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '406015C', name: 'APORTE DE LAS TIC EN LA ENSEÑANZA DE LAS CIENCIAS', credits: 3, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '505134C', name: 'EDICIÓN DE PARTITURAS', credits: 2, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '750002C', name: 'INFORMÁTICA I', credits: 3, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '750011C', name: 'FUNDAMENTOS DE PROGRAMACIÓN', credits: 3, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '750012C', name: 'FUNDAMENTOS DE PROGRAMACIÓN IMPERATIVA', credits: 3, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '750007C', name: 'FUNDAMENTOS Y APLICACIONES DE LA PROGRAMACIÓN COMPUTACIONAL', credits: 4, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '770001C', name: 'CIENCIAS DE LOS MATERIALES', credits: 3, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '710004C', name: 'TALLER DE INGENIERÍA II', credits: 2, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '102081C', name: 'INSECTOS Y SOCIEDAD', credits: 3, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '1303004C', name: 'FUNDAMENTOS DE PROGRAMACIÓN PARA ECONOMÍA', credits: 4, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '303025C', name: 'CIENCIAS AMBIENTALES', credits: 3, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '406001C', name: 'FUNDAMENTACIÓN EN CIENCIAS, TECNOLOGÍA, SOCIEDAD Y AMBIENTE', credits: 3, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '416047C', name: 'NUMEROS Y ESTADISTICAS PARA PENSAR LA EDUCACIÓN POPULAR', credits: 3, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '607008C', name: 'RAZA, ETNIA, RACISMO Y SALUD PÚBLICA', credits: 3, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '111061C', name: 'FUNDAMENTOS INICIALES DE MATEMÁTICA UNIVERSITARIA', credits: 3, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },
    { id: '730111C', name: 'TALLER TECNOLÓGICO I: GESTIÓN DE LA CONSERVACIÓN', credits: 3, type: 'EC', category: 'Científico Tecnológico', prerequisites: [] },

    // === COMPONENTE FORMACIÓN SOCIAL Y CIUDADANA ===
    { id: '415007C', name: 'FORMACIÓN CIUDADANA Y CONSTITUCIÓN POLÍTICA DE COLOMBIA', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '304035C', name: 'GÉNERO, PLURALIDAD Y DIVERSIDAD', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '506015C', name: 'COMUNICACIÓN, GÉNERO Y DIVERSIDAD', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '415011C', name: 'EDUCACIÓN COMUNIDADES NEGRAS, AFROCOLOMBIANAS, RAIZALES, PALENQUERAS', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '801042C', name: 'INTRODUCCIÓN AL DERECHO Y CONSTITUCIÓN POLÍTICA', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '730025C', name: 'SEMINARIO EN CONSTITUCIÓN, LEGISLACIÓN Y ÉTICA DE LA PROFESIÓN', credits: 2, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '730011C', name: 'FUNDAMENTOS SISTEMAS SOCIOECOLÓGICOS', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '204058C', name: 'RESOLUCIÓN DE CONFLICTOS EN LA ESCUELA GÉNERO Y DIVERSIDAD', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '102061C', name: 'ÉTICA Y RESPONSABILIDAD SOCIAL', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '760018C', name: 'INGENIERÍA Y SOCIEDAD', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '801078C', name: 'CIENCIAS HUMANAS', credits: 2, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '203001C', name: 'CULTURA DE PAZ/CONSTRUCCIÓN DE CULTURA DE PAZ', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '801112C', name: 'RESPONSABILIDAD SOCIAL Y GESTIÓN HUMANA EN EL SECTOR PÚBLICO', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '102062C', name: 'FUNDAMENTOS DE SUSTENTABILIDAD Y AMBIENTE', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '201002C', name: 'CIENCIAS SOCIALES Y CIUDADANÍA', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '802027C', name: 'MECANISMOS DE CONTROL ORGANIZACIONES CIVILES Y PARTICIPACIÓN CIUDADANA', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '730012C', name: 'FUNDAMENTOS DE PROCESOS SOCIALES', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '202023C', name: 'LEGISLACIÓN EDUCATIVA EN COLOMBIA', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '201001C', name: 'ANTROPOLOGÍA Y DEMOCRACIA', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '203013C', name: 'ÉTICA Y POLÍTICA', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '406008C', name: 'PENSAMIENTO HISTÓRICO - FILOSÓFICO EN LA ENSEÑANZA DE LAS CIENCIAS', credits: 2, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '406025C', name: 'POLÍTICAS PÚBLICAS EDUCATIVAS DEL ESTADO', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '507089C', name: 'PROYECTO BIOSFERA - DISEÑO ONTOLÓGICO', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '607007C', name: 'COMER: SABORES, LUCHAS Y SALUD PÚBLICA', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '607008C', name: 'RAZA, ETNIA, RACISMO Y SALUD PÚBLICA', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '607010C', name: 'SEGURIDAD FINANCIERA Y DECISIONES RESPONSABLES', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '801142C', name: 'ÉTICA EN LOS NEGOCIOS, RESPONSABILIDAD SOCIAL Y SOSTENIBILIDAD AMBIENTAL', credits: 2, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '620021C', name: 'DISCAPACIDAD, SOCIEDAD Y CULTURA', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '106036C', name: 'NORMATIVIDAD Y ÉTICA PROFESIONAL', credits: 2, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '406018C', name: 'EL PENSAMIENTO DOCENTE', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '406006C', name: 'COSMOVISIONES Y TEORÍAS DEL CONOCIMIENTO', credits: 2, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '404047C', name: 'EDUCACIÓN PARA LA PAZ', credits: 2, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '201069C', name: 'DISCRIMINACIÓN, EMPODERAMIENTO Y CIUDADANÍA', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '415037C', name: 'EDUCACIÓN SUPERIOR Y CONTEXTOS SOCIOPOLÍTICOS Y PROFESIONALES CONTEMPORÁNEOS', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '415041C', name: 'PEDAGOGÍA, ÉTICA E INFANCIA', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: 'D02006C', name: 'CÁTEDRA DE LA JEP', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '303002C', name: 'FILOSOFÍA POLÍTICA', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '303003C', name: 'TEORÍA SOCIAL', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '416033C', name: 'ORGANIZACIÓN Y DINÁMICAS DE LOS GRUPOS', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '801107C', name: 'HABILIDADES GERENCIALES', credits: 2, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '201076C', name: 'DEBATES EN HISTORIA CONTEMPORÁNEA', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '201077C', name: 'CULTURA PARTICIPATIVA COMUNITARIA Y GESTIÓN PÚBLICA', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '416041C', name: 'EDUCACIÓN EN DERECHOS HUMANOS', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    { id: '417031C', name: 'CUESTIONES SOCIOCULTURALES PARA LA ENSEÑANZA DE LA FÍSICA', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana', prerequisites: [] },
    
    // === COMPONENTE DE LENGUAJE Y COMUNICACIÓN ===
    // Nivel I de español
    { id: '204133C', name: 'COMPRENSIÓN Y PRODUCCIÓN DE TEXTOS ACADÉMICOS GENERALES', credits: 2, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '203012C', name: 'ESPAÑOL Y COMUNICACIÓN I', credits: 2, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '415008C', name: 'TALLER DE LECTURA Y ESCRITURA I', credits: 2, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '416009C', name: 'HERRAMIENTAS PARA PENSAR Y RECREAR - ARGUMENTOS Y TEXTOS ACADÉMICOS', credits: 2, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '416035C', name: 'ARTESANIAS DE LA PRODUCCION INTELECTUAL I', credits: 3, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '416045C', name: 'ARTESANIAS DE LA PRODUCCION INTELECTUAL II', credits: 3, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    // Nivel II de español
    { id: '204161C', name: 'COMPRENSIÓN Y PRODUCCIÓN DE TEXTOS ACADÉMICOS DE LAS DISCIPLINAS - SALUD Y PSICOLOGÍA', credits: 2, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '204162C', name: 'COMPRENSIÓN Y PRODUCCIÓN DE TEXTOS ACADÉMICOS DE LAS DISCIPLINAS - INGENIERÍA', credits: 2, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '204163C', name: 'COMPRENSIÓN Y PRODUCCIÓN DE TEXTOS ACADÉMICOS DE LAS DISCIPLINAS - DERECHO Y ADMINISTRACIÓN', credits: 2, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '204164C', name: 'COMPRENSIÓN Y PRODUCCIÓN DE TEXTOS ACADÉMICOS DE LAS DISCIPLINAS - CIENCIAS NATURALES Y EXACTAS', credits: 2, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '204165C', name: 'COMPRENSIÓN Y PRODUCCIÓN DE TEXTOS ACADÉMICOS DE LAS DISCIPLINAS - CIENCIAS ECONÓMICAS Y SOCIALES', credits: 2, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '204166C', name: 'COMPRENSIÓN Y PRODUCCIÓN DE TEXTOS ACADÉMICOS DE LAS DISCIPLINAS - EDUCACIÓN, ARTES Y HUMANIDADES', credits: 2, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '203027C', name: 'ESPAÑOL Y COMUNICACIÓN II', credits: 2, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '416046C', name: 'ESCRITURA Y LECTURA DE TEXTOS ACADÉMICOS EN EDUCACIÓN', credits: 3, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    // Suficiencia en lengua extranjera
    { id: '204025C', name: 'INGLÉS CON FINES GENERALES Y ACADÉMICOS I', credits: 2, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '204026C', name: 'INGLÉS CON FINES GENERALES Y ACADÉMICOS II', credits: 2, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '204027C', name: 'INGLÉS CON FINES GENERALES Y ACADÉMICOS III', credits: 2, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '204154C', name: 'INGLÉS CON FINES GENERALES Y ACADÉMICOS IV', credits: 2, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '204155C', name: 'INGLÉS CON FINES GENERALES Y ACADÉMICOS V', credits: 2, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    // Otras asignaturas
    { id: '204024C', name: 'LECTURA CRÍTICA', credits: 3, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '505001C', name: 'APRENDAMOS BRAILLE', credits: 2, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '106013C', name: 'SEMINARIO DE CIENCIAS EN INGLÉS', credits: 2, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '417002C', name: 'LENGUAJE, COMUNICACIÓN Y ENSEÑANZA DE LAS CIENCIAS', credits: 3, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '410003C', name: 'HERRAMIENTAS PARA PENSAR Y RECREAR RELATOS Y ESCRITURAS NARRATIVAS', credits: 3, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '406039C', name: 'SEMINARIO DE PRÁCTICA DOCENTE I', credits: 3, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '802052C', name: 'METODOLOGÍA DE LA INVESTIGACIÓN', credits: 3, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '102049C', name: 'TALLER DE ESCRITURA Y DIVULGACIÓN CIENTÍFICA', credits: 2, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '106033C', name: 'SEMINARIO DE LECTURA Y ESCRITURA CIENTÍFICA', credits: 2, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '415009C', name: 'TALLER DE LECTURA Y ESCRITURA II', credits: 2, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '504004C', name: 'TALLER DE TEATRO EN INGLÉS', credits: 4, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '506011C', name: 'ANÁLISIS TEXTUAL I', credits: 2, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '506016C', name: 'ESCRITURA I', credits: 4, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '750040C', name: 'DISEÑO DE CONTENIDO PARA INTERFACES DE USUARIO', credits: 3, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '202006C', name: 'LENGUAJE Y COMUNICACIÓN II', credits: 3, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '202024C', name: 'LENGUAJE Y COMUNICACIÓN III', credits: 3, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '202031C', name: 'LENGUAJE Y COMUNICACIÓN IV', credits: 3, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '204139C', name: 'ESCRITURA DE TRABAJO DE GRADO', credits: 3, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '620037C', name: 'HABILIDADES ORALES PARA LA VIDA PROFESIONAL', credits: 3, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '801195C', name: 'TALLER DE ESCRITURA CIENTÍFICA', credits: 3, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: 'D01009C', name: 'LÓGICA Y ARGUMENTACIÓN I', credits: 3, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: 'D01010C', name: 'LÓGICA Y ARGUMENTACIÓN II', credits: 3, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: 'D02002C', name: 'TALLER DE COMPRENSIÓN DE TEXTOS', credits: 2, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '204270M', name: 'NASA YUWE I', credits: 3, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    { id: '204271M', name: 'NASA YUWE II', credits: 3, type: 'EC', category: 'Lenguaje y Comunicación', prerequisites: [] },
    
    // === COMPONENTE DE ESTILOS DE VIDA SALUDABLE ===
    { id: '603032C', name: 'HABILIDADES PARA LA VIDA: DESCUBRIENDO EL POTENCIAL DEL SER EMOCIONAL, AFECTIVO, COGNITIVO Y SOCIAL', credits: 3, type: 'EC', category: 'Estilos de Vida Saludable', prerequisites: [] },
    { id: '404032C', name: 'DEPORTE FORMATIVO', credits: 3, type: 'EC', category: 'Estilos de Vida Saludable', prerequisites: [] },
    { id: '410029C', name: 'HATHA YOGA', credits: 3, type: 'EC', category: 'Estilos de Vida Saludable', prerequisites: [] },
    { id: '607003C', name: 'INTRODUCCIÓN A LAS INTERVENCIONES ASISTIDAS CON ANIMALES', credits: 3, type: 'EC', category: 'Estilos de Vida Saludable', prerequisites: [] },
    { id: '607004C', name: 'APNEA: MENTE, CUERPO Y VIDA SALUDABLE', credits: 3, type: 'EC', category: 'Estilos de Vida Saludable', prerequisites: [] },
    { id: '404002C', name: 'DEPORTE Y SALUD', credits: 2, type: 'EC', category: 'Estilos de Vida Saludable', prerequisites: [] },
    { id: '402002C', name: 'CORPORALIDAD EN MOVIMIENTO (PSICOMOTRICIDAD)', credits: 2, type: 'EC', category: 'Estilos de Vida Saludable', prerequisites: [] },
    { id: '415026C', name: 'JUEGO Y MOVIMIENTO PARA LA VIDA', credits: 3, type: 'EC', category: 'Estilos de Vida Saludable', prerequisites: [] },
    { id: '415024C', name: 'AUTOCUIDADO Y PROYECTO DE VIDA SALUDABLE', credits: 3, type: 'EC', category: 'Estilos de Vida Saludable', prerequisites: [] },
    { id: '605010C', name: 'PRINCIPIO DE NUTRICIÓN, ALIMENTACIÓN Y SALUD', credits: 3, type: 'EC', category: 'Estilos de Vida Saludable', prerequisites: [] },
    { id: '404028C', name: 'DANZA Y EXPRESIÓN CORPORAL', credits: 3, type: 'EC', category: 'Estilos de Vida Saludable', prerequisites: [] },
    { id: '504070C', name: 'PRÁCTICAS ARTÍSTICAS, CUERPO Y SALUD MENTAL', credits: 3, type: 'EC', category: 'Estilos de Vida Saludable', prerequisites: [] },
    { id: '411003C', name: 'PROYECTO DE VIDA I', credits: 3, type: 'EC', category: 'Estilos de Vida Saludable', prerequisites: [] },
    { id: '411004C', name: 'PROYECTO DE VIDA II', credits: 3, type: 'EC', category: 'Estilos de Vida Saludable', prerequisites: [] },
    { id: '404010C', name: 'DEPORTE FORMATIVO', credits: 2, type: 'EC', category: 'Estilos de Vida Saludable', prerequisites: [] },
    { id: '404011C', name: 'JUEGO Y MOVIMIENTO PARA LA VIDA', credits: 2, type: 'EC', category: 'Estilos de Vida Saludable', prerequisites: [] },

    // === COMPONENTE ARTÍSTICO HUMANÍSTICO ===
    { id: '402051C', name: 'VIDA UNIVERSITARIA I: ENCUENTROS CON LA UNIVERSIDAD', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '204124C', name: 'NARRATIVAS DE VIDA', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '417008C', name: 'CIENCIA, CULTURA Y CREATIVIDAD', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '402014C', name: 'LÚDICA Y ESTESIS EN LA CONSTITUCIÓN DEL SER HUMANO', credits: 2, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '504001C', name: 'EL ARTE DE EXPRESARSE EN PÚBLICO', credits: 4, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '504002C', name: 'TALLER DE CREATIVIDAD AUDIOVISUAL', credits: 4, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '504003C', name: 'TALLER DE GUION AUDIOVISUAL PARA PRINCIPIANTES', credits: 4, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '504019C', name: 'ESTÉTICAS DE LA RESISTENCIA', credits: 4, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '504037C', name: 'TALLER DE APRECIACIÓN DEL TEATRO', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '504038C', name: 'ACTUACIÓN ANTE CÁMARAS', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '504048C', name: 'CONCEPTUALIZACIÓN Y DISEÑO DE PROYECTOS CULTURALES', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '504049C', name: 'ANÁLISIS ACTIVO A PERSONAJES FEMENINOS DE LA DRAMATURGIA', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '504050C', name: 'HERRAMIENTAS DIDÁCTICAS PARA LA ESCUELA - TÉCNICAS BÁSICAS DE CONSTRUCCIÓN Y MANEJO DE TÍTERES', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '504051C', name: 'JUEGOS ACROBÁTICOS EXPRESIÓN CORPORAL PARA NO ACTORES', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '504052C', name: 'TEATRO, SUEÑO Y CREACIÓN', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '504053C', name: 'TEATROS Y TEATRALIDADES DEL MUNDO', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '504057C', name: 'BALLET FIT:FLEXIBILIDAD, ELASTICIDAD Y FUERZA PARA PRINCIPIANTES', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '504058C', name: 'DANZA Y FRONTERA: CUERPOS, MOVIMIENTOS Y DECOLONIALIDAD', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '504063C', name: 'PRÁCTICAS ARTÍSTICAS Y TRABAJO EN COMUNIDAD', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '505047C', name: 'CANTO, POSTURA Y SALUD', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '505082C', name: 'HISTORIA DE LA MÚSICA EN COLOMBIA', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '506046C', name: 'APRECIACIÓN DEL CINE', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '507043C', name: 'MORFOLOGÍA', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '507048C', name: 'PRODUCCIÓN INTERSUBJETIVA DEL ESPACIO FÍSICO Y SOCIAL', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '507088C', name: 'NUEVAS DRAMATURGIAS DE LA IMAGEN', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '509036C', name: 'ARTE, LITERATURA Y FILOSOFÍA', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '607009C', name: 'COSTURERO DE UNIVALLE: BORDADOS QUE HABLAN Y TEJIDOS QUE CUENTAN HISTORIAS', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '620012C', name: 'MOVIMIENTO CORPORAL CONSCIENTE', credits: 2, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '710061C', name: 'ROBOTS, HISTORIA Y FICCIÓN', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '801126C', name: 'HUMANISMO, PENSAMIENTO ADMINISTRATIVO Y ORGANIZACIONES', credits: 2, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '410005C', name: 'TALLER MULTIMODAL DE EXPRESIÓN CORPORAL Y MOVIMIENTO AUTÉNTICO', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '626001C', name: 'HISTORIA IDEAS EN CIENCIAS DE LA SALUD', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '509039C', name: 'CROMÁTICA EXPERIMENTAL: EXPLORANDO LOS LÍMITES DEL COLOR', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '416010C', name: 'TALLER MULTIMODAL DE LENGUAJES LÚDICO - CREATIVOS - EXPERIENCIAS INTEGRADORAS', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '416046C', name: 'NARRATIVAS COMUNITARIAS TECNOMEDIADAS', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '504060C', name: 'HERRAMIENTAS BÁSICAS DESDE LAS ARTES ESCÉNICAS PARA EL DESARROLLO PEDAGÓGICO EN EL AULA', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '504062C', name: 'REFLEXIONES EN TORNO AL CUERPO Y EL GÉNERO: TENSIONES Y RUPTURAS', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '505069C', name: 'HISTORIA DE LA MÚSICA LATINOAMERICANA', credits: 2, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '505100C', name: 'HISTORIA DE LA MÚSICA I', credits: 4, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '505101C', name: 'HISTORIA DE LA MÚSICA II', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '505062C', name: 'HISTORIA DE LA MUSICA III', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '505102C', name: 'HISTORIA DE LA MÚSICA IV', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '506047C', name: 'HISTORIA DEL CINE', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '506048C', name: 'LENGUAJE NARRATIVO Y EXPRESIÓN LÚDICO TEATRAL', credits: 2, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '417028C', name: 'HISTORIA Y ENSEÑANZA DE LAS TECNOLOGÍAS', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '504071C', name: 'TALLER DE EXPRESIÓN ORAL Y RETÓRICA', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '509050C', name: 'ESCRITURA Y CRÍTICA EN LAS ARTES', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    { id: '509051C', name: 'FILOSOFIA Y LITERATURA: CUATRO ENCUENTROS MODERNOS', credits: 3, type: 'EC', category: 'Artístico Humanístico', prerequisites: [] },
    
    // === ASIGNATURAS QUE COMPARTEN VARIOS COMPONENTES ===
    { id: '607005C', name: 'CINE Y SALUD: CONSTRUYENDO UNA MIRADA CRÍTICA DESDE EL SALUBRISMO Y EL ARTE', credits: 3, type: 'EC', category: 'Formación social y ciudadana, Lenguaje y comunicación, Artístico y humanístico', prerequisites: [] },
    { id: '701001C', name: 'INSERCIÓN A LA VIDA UNIVERSITARIA', credits: 2, type: 'EC', category: 'Lenguaje y Comunicación, Estilos de Vida Saludable, Artístico Humanístico', prerequisites: [] },
    { id: '760007C', name: 'PENSAMIENTO SISTÉMICO Y ORGANIZACIONES', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana, Científico tecnológico', prerequisites: [] },
    { id: '701003C', name: 'INTRODUCCIÓN A LA INGENIERÍA', credits: 2, type: 'EC', category: 'Científico tecnológico, Lenguaje y Comunicación', prerequisites: [] },
    { id: '701002C', name: 'TALLER DE INGENIERÍA I', credits: 3, type: 'EC', category: 'Científico Tecnológico, Lenguaje y Comunicación', prerequisites: [] },
    { id: '780022C', name: 'SEMINARIO DE TRABAJO DE GRADO', credits: 2, type: 'EC', category: 'Formación Social y Ciudadana, Lenguaje y comunicación, Científico tecnológico', prerequisites: [] },
    { id: '780032C', name: 'EXPERIMENTACIÓN TÉCNICA Y MEDICIONES', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana, Lenguaje y comunicación, Científico tecnológico', prerequisites: [] },
    { id: '780033C', name: 'VIDA Y CONTEXTO UNIVERSITARIO', credits: 1, type: 'EC', category: 'Lenguaje y Comunicación, Estilos de Vida Saludable, Artístico Humanístico', prerequisites: [] },
    { id: '770019C', name: 'TALLER DE INGENIERÍA DE MATERIALES', credits: 3, type: 'EC', category: 'Lenguaje y comunicación, Científico-tecnológico', prerequisites: [] },
    { id: '504061C', name: 'EXPRESIÓN ORAL Y RETÓRICA', credits: 2, type: 'EC', category: 'Artístico Humanístico, Lenguaje y Comunicación', prerequisites: [] },
    { id: '745021C', name: 'TALLER DE INGENIERÍA DE ALIMENTOS II', credits: 3, type: 'EC', category: 'Lenguaje y Comunicación, Científico Tecnológico', prerequisites: [] },
    { id: '710025C', name: 'TALLER TECNOLÓGICO II', credits: 3, type: 'EC', category: 'Lenguaje y comunicación, Científico tecnológico', prerequisites: [] },
    { id: '417010C', name: 'CREATIVIDAD, CULTURA Y TECNOLOGÍA', credits: 3, type: 'EC', category: 'Artístico Humanístico, Científico Tecnológico', prerequisites: [] },
    { id: '415039C', name: 'EMOCIONES Y EDUCACIÓN', credits: 3, type: 'EC', category: 'Formación Social y Ciudadana, Estilos de vida saludable, Artístico Humanístico', prerequisites: [] },
    
    // === ASIGNATURAS DE EMPRENDIMIENTO ===
    { id: '507098C', name: 'EMPRENDIMIENTO, CULTURA Y CIUDAD', credits: 3, type: 'EC', category: 'Emprendimiento', prerequisites: [] },
    { id: '507099C', name: 'DESARROLLO DE PROYECTO EMPRENDEDOR', credits: 3, type: 'EC', category: 'Emprendimiento', prerequisites: [] },
    { id: '507100C', name: 'DESARROLLO DE LA CREATIVIDAD', credits: 3, type: 'EC', category: 'Emprendimiento', prerequisites: [] },
    { id: '507101C', name: 'DESARROLLO DE CLIENTES', credits: 3, type: 'EC', category: 'Emprendimiento', prerequisites: [] }
];

// Exportar para uso en el navegador y Node.js
if (typeof window !== 'undefined') {
    window.ELECTIVAS_FG = ELECTIVAS_FG;
}

if (typeof module !== 'undefined' && module.exports) {
    module.exports = { ELECTIVAS_FG };
}
