// =================== DATOS DEL PENSUM - DISEÑO INDUSTRIAL Res. 188===================

const PENSUM_DI = [
    // Requisito de Inglés (Área Básica pero con conteo separado)
    { id: '204025C', name: 'INGLÉS CON FINES GENERALES Y ACADÉM. I', credits: 2, type: 'AB', category: 'english', prerequisites: [] },
    { id: '204026C', name: 'INGLÉS FINES GENERALES Y ACADÉMICOS II', credits: 2, type: 'AB', category: 'english', prerequisites: ['204025C'] },
    { id: '204027C', name: 'INGLÉS CON FINES GENERALES Y ACADÉM. III', credits: 2, type: 'AB', category: 'english', prerequisites: ['204026C'] },
    { id: '204028C', name: 'INGLÉS FINES GENERALES Y ACADÉMICOS IV', credits: 2, type: 'AB', category: 'english', prerequisites: ['204027C'] },
    
    // Ciclo Básico
    { id: '506026C', name: 'ESCRITURA, EXPRESIÓN Y COMUNICACIÓN', credits: 2, type: 'AB', prerequisites: [] },
    { id: '507048C', name: 'PRODUCCIÓN INTERSUBJETIVA DEL ESPACIO FÍSICO Y SOCIAL', credits: 2, type: 'AB', prerequisites: [] },
    { id: '507031C', name: 'DISEÑO MUNDO', credits: 3, type: 'AB', prerequisites: [] },
    { id: '507044C', name: 'DISEÑO PARA LA PAZ SOSTENIBLE', credits: 2, type: 'AB', prerequisites: [] },
    { id: '507026C', name: 'SEMINARIO DE INVESTIGACIÓN', credits: 2, type: 'AB', prerequisites: [] },
    { id: '507046C', name: 'FUNDAMENTOS SOCIALES Y CULTURALES DEL DISEÑO', credits: 2, type: 'AB', prerequisites: [] },
    { id: '507055C', name: 'PERCEPCIÓN VISUAL', credits: 2, type: 'AB', prerequisites: [] },
    { id: '507017C', name: 'MÉTODOS DE DISEÑO', credits: 2, type: 'AB', prerequisites: [] },
    { id: '507008C', name: 'CREACIÓN DE LA FORMA', credits: 2, type: 'AB', prerequisites: [] },
    { id: '507053C', name: 'ESTUDIOS VISUALES', credits: 2, type: 'AB', prerequisites: [] },
    { id: '507010C', name: 'GEOMETRÍA', credits: 2, type: 'AB', prerequisites: [] },
    { id: '507012C', name: 'INTRODUCCIÓN MATERIALES Y PROCESOS', credits: 2, type: 'AB', prerequisites: [] },
    { id: '507013C', name: 'MATEMÁTICAS', credits: 2, type: 'AB', prerequisites: [] },
    { id: '507009C', name: 'FÍSICA PARA EL DISEÑO', credits: 2, type: 'AB', prerequisites: [] },
    { id: '507025C', name: 'PROYECTO - SER HUMANO', credits: 7, type: 'AB', prerequisites: [] },
    { id: '507024C', name: 'PROYECTOS - RELACIONES Y VÍNCULOS', credits: 4, type: 'AB', prerequisites: [] },
    { id: '507021C', name: 'PROYECTOS - ESTRUCTURAS Y AUTONOMÍAS', credits: 4, type: 'AB', prerequisites: [] },

    // Ciclo Profesional (Componente Profesional)
    { id: '507111C', name: 'DISEÑO COLONIAL Y MODERNIDAD D.I.', credits: 2, type: 'AP', prerequisites: [] },
    { id: '507035C', name: 'DISIDENCIAS Y RESISTENCIAS', credits: 3, type: 'AP', prerequisites: [] },
    { id: '507036C', name: 'ESTUDIOS CRÍTICOS DEL DISEÑO', credits: 3, type: 'AP', prerequisites: [] },
    { id: '507047C', name: 'HERRAMIENTAS DIGITALES - REPRESENTACIÓN', credits: 2, type: 'AP', prerequisites: [] },
    { id: '507014C', name: 'MATERIALES Y PROCESOS - METALES', credits: 3, type: 'AP', prerequisites: ['507012C'] },
    { id: '507011C', name: 'HERRAMIENTAS DIGITALES - PROGRAMACIÓN', credits: 2, type: 'AP', prerequisites: [] },
    { id: '507015C', name: 'MATERIALES Y PROCESOS - NUEVOS MATERIALES', credits: 3, type: 'AP', prerequisites: ['507012C'] },
    { id: '507023C', name: 'PROYECTO - PRODUCTO', credits: 7, type: 'AP', prerequisites: [] },
    { id: '507059C', name: 'HERRAMIENTAS DIGITALES - COMPROBACIÓN', credits: 2, type: 'AP', prerequisites: [] },
    { id: '507115C', name: 'PROYECTO - GESTIÓN', credits: 7, type: 'AP', prerequisites: [] },
    { id: '507016C', name: 'MATERIALES Y PROCESOS - POLIMEROS', credits: 3, type: 'AP', prerequisites: ['507012C'] },
    { id: '507020C', name: 'PROYECTO - ENTORNO', credits: 7, type: 'AP', prerequisites: [] },
    { id: '507060C', name: 'HERRAMIENTAS DIGITALES - CREACIÓN VISUALIZACIÓN', credits: 2, type: 'AP', prerequisites: [] },
    { id: '507019C', name: 'PROYECTO - BIOSFERA', credits: 7, type: 'AP', prerequisites: [] },
    { id: '507058C', name: 'HERRAMIENTAS DIGITALES - SIMULACIÓN', credits: 2, type: 'AP', prerequisites: [] },
    { id: '507096C', name: 'PROYECTO FINAL FORMULACIÓN', credits: 3, type: 'AP', prerequisites: ['507026C'] },
    { id: '507095C', name: 'PROYECTO FINAL DESARROLLO', credits: 4, type: 'AP', prerequisites: ['507096C'] },

    // Electivas Profesionales
    { id: '507092C', name: 'BIOMIMESIS', credits: 2, type: 'EP', prerequisites: [] },
    { id: '507082C', name: 'COLOR', credits: 3, type: 'EP', prerequisites: [] },
    { id: '507057C', name: 'CREACIÓN CON MADERA', credits: 2, type: 'EP', prerequisites: [] },
    { id: '507083C', name: 'CRÍTICA DE LAS MERCANCÍAS Y EL CONSUMO', credits: 3, type: 'EP', prerequisites: [] },
    { id: '507062C', name: 'DIBUJO TÉCNICO PARA DISEÑO INDUSTRIAL', credits: 2, type: 'EP', prerequisites: [] },
    { id: '507090C', name: 'DISEÑO DE APLICACIONES MÓVILES', credits: 3, type: 'EP', prerequisites: [] },
    { id: '507093C', name: 'DISEÑO Y PROTOTIPADO DE SISTEMAS ROBÓTICOS', credits: 3, type: 'EP', prerequisites: [] },
    { id: '507061C', name: 'ESTRATEGIAS DE ECODISEÑO', credits: 2, type: 'EP', prerequisites: [] },
    { id: '507084C', name: 'ESTUDIOS CRÍTICOS SOBRE LOS RESIDUOS', credits: 3, type: 'EP', prerequisites: [] },
    { id: '507094C', name: 'PRÁCTICAS ESCRITURALES', credits: 2, type: 'EP', prerequisites: [] },
    { id: '507109C', name: 'SOSTENIBILIDAD EN LA INDUSTRIA TEXTIL', credits: 2, type: 'EP', prerequisites: [] },
    { id: '507105C', name: 'MORFOLOGÍA EXPERIMENTAL EN EL DISEÑO INDUSTRIAL', credits: 4, type: 'EP', prerequisites: [] },
    { id: '507106C', name: 'PROCESOS DE FABRICACION ADITIVA - IMPRESION TRIDIMENSIONAL (3D)', credits: 3, type: 'EP', prerequisites: [] },
    { id: '507110C', name: 'TÉCNICAS DE PROTOTIPADO RÁPIDO', credits: 3, type: 'EP', prerequisites: [] },
    { id: '507108C', name: 'EL GÉNERO EN LOS OBJETOS', credits: 3, type: 'EP', prerequisites: [] },
    { id: '507113C', name: 'MARKETING DE PRODUCTO', credits: 3, type: 'EP', prerequisites: [] },
    { id: '507112C', name: 'ELEMENTOS PARA DISEÑO DE INTERIORES', credits: 3, type: 'EP', prerequisites: [] },
    { id: '507114C', name: 'PRÁCTICAS ESCRITURALES II', credits: 3, type: 'EP', prerequisites: [] },
    { id: '507051C', name: 'PRÁCTICA EN INVESTIGACIÓN-CREACIÓN', credits: 3, type: 'EP', prerequisites: [] },
    { id: '507118C', name: 'PRODUCCIÓN DE PLATAFORMAS CULTURALES PARA ARTE Y DISEÑO', credits: 3, type: 'EP', prerequisites: [] },
    { id: '507122C', name: 'DISEÑO INDUSTRIAL CONTEMPORÁNEO', credits: 3, type: 'EP', prerequisites: [] },
    { id: '507121C', name: 'REUSO Y RECICLAJE CREATIVO', credits: 3, type: 'EP', prerequisites: [] },
    { id: '507120C', name: 'MODELOS EN REPETICIÓN', credits: 3, type: 'EP', prerequisites: [] },
    { id: '507119C', name: 'DISEÑO + ARTE CONTEMPORÁNEO', credits: 3, type: 'EP', prerequisites: [] }
];
